### ISSUE TITLE
Right click commands not possible

### ISSUE THREAD

**Issue by ruyanve** [ChippedChap/CleaningPriority#1]
Loaded CleaningPriority (no errors on startup), started a new game: Lost Tribe, Phoebe, medium difficulty, commitment mode, 30% world, random tile, random pawns.
As soon as the map is loaded and game is unpaused the following error keeps spamming the log: https://hastebin.com/ivositeyir.css

Hovering over the cleaning zone icon in the lower right makes the UI disappear except for the other vanilla icons in the lower right and the pawn icons on the top. Log shows this: https://hastebin.com/duxunimofu.sql

Here's the full log: https://hastebin.com/ukidupicat.cs

I'd be happy to help with further testing! <3

**Comment by ChippedChap** [comment]
I tried to reproduce the bug you are having by generating a game the same way you did. For some reason the mod continued to work without any issues.

I pushed a change that might fix the issue. Based on the logs the priority list seems to get null references. When loading/saving, null references are now stripped from the priority list. If you have the time, a zip of the mod with this change is attached so you can test it.
[CleaningPriority.zip](https://github.com/ChippedChap/CleaningPriority/files/2597964/CleaningPriority.zip)

**Comment by ruyanve** [comment]
Right click commands work, area view icon works, log is clear.
Great job mate, thank you so much!

If you ever need any help testing stuff, don't hesitate to poke me! <3

**Comment by ruyanve** [comment]
Now I get the following as soon as there's an area set to cleaning: https://hastebin.com/ivayogevad.sql

Tested with the version you posted above

**Comment by ChippedChap** [comment]
Oh, I'm pretty sure that's from a completely different cleaning mod. The class having the exception is WorkGiver_PriorityClean but the WorkGiver in this mod is called WorkGiver_CleanFilthPrioritized.

I'll keep this open just in case the error is being caused by an underlying issue.

**Comment by ruyanve** [comment]
Ah ok, it must be this one then: https://github.com/n-fisher/PriorityClean-Mod

**Comment by ChippedChap** [comment]
Looking at that mods code, there seems to be no real underlying issue.

I’ll note later that this may be incompatible with other cleaning mods.
