### ISSUE TITLE
How to Instal non-steam version?

### ISSUE THREAD

**Issue by Kibawan** [ChippedChap/CleaningPriority#3]
Hi.

A about 2 days i'm trying to make the CP to work, but nothing happens. I realy want have this mod in my ever growing list of indispensables! So what i did, i download the master and put on the Mods folder as usual, nothing happens, i try several times with and without other mods, then, i try to put just the CP folder inside the master on the mods folder and again, nothing, there anything to do yet? 

Any help is apreciate. 0/

**Comment by ChippedChap** [comment]
Hello,

It seems like you downloaded the master and then put the first folder named CleaningPriority in your mod folder. The master includes all source files and the actual mod files are buried there, so it won't work. The working mod file is in CleaningPriority/Distribution. The single folder in CleaningPriority/Distribution is what you're supposed to put in the mods folder.

You were supposed to get the working Cleaning Priority folder directly from the [releases page](https://github.com/ChippedChap/CleaningPriority/releases). The releases page has direct downloads for the folder you were supposed to put in your mod folder.
